### ISSUE TITLE
Environment variable becomes DDEV_MAILPIT_HTTP_PORT

### ISSUE THREAD

**Issue by rfay** [ddev/ddev-browsersync#46]
In DDEV v1.22.2+, the required environment variable becomes DDEV_MAILPIT_HTTP_PORT instead of DDEV_MAILHOG_PORT. However, it's not reasonable to change this right away. As of DDEV v1.22.3, DDEV_MAILHOG_PORT is supported again as an alias to DDEV_MAILPIT_HTTP_PORT.

So after a few months we can update this and do a new release.

**Comment by tyler36** [comment]
For future self, this is in `docker-compose.browsersync.yaml`

```diff
    environment:
-      - HTTP_EXPOSE=${DDEV_ROUTER_HTTP_PORT}:80,${DDEV_MAILHOG_PORT}:8025,3001:3000
-      - HTTPS_EXPOSE=${DDEV_ROUTER_HTTPS_PORT}:80,${DDEV_MAILHOG_HTTPS_PORT}:8025,3000:3000
+      - HTTP_EXPOSE=${DDEV_ROUTER_HTTP_PORT}:80,${DDEV_MAILPIT_HTTP_PORT}:8025,3001:3000
+      - HTTPS_EXPOSE=${DDEV_ROUTER_HTTPS_PORT}:80,${DDEV_MAILPIT_HTTPS_PORT}:8025,3000:3000
```
