### ISSUE TITLE
How to autostart browsersync and clear drupal 8-10 cache on startup

### ISSUE THREAD

**Issue by barkbyte** [ddev/ddev-browsersync#50]
I was looking for this and then tried this out....
helpful to me... hope it helps someone else
Add the following to your ddev config.yaml file

hooks:
  post-start:
    - exec: "drush cache:rebuild"
    - exec-host: "ddev browsersync"

**Comment by tyler36** [comment]
Thank you for sharing. Care to do PR?

**Comment by tyler36** [comment]
Closing.
Developers will be able to find this if they search for "autostart".

PRs are welcome if you feel the docs should include this.
