### ISSUE TITLE
FR: autostart browsersync by default

### ISSUE THREAD

**Issue by tyler36** [ddev/ddev-browsersync#58]
In PR #56 , @rfay said

> I wonder if you'll ever want to automate it so the daemon runs automatically with web_extra_daemons.

What are everyones opinions on this?

**Comment by tyler36** [comment]
Personally, I usually only enable browsersync when I'm working on frontend of a site. 
I tend to spend most of my time writing PHPunit tests these days so I generally don't have a need to use.

To be honest, I find myself working more and more with Vite, which has auto-refresh, and thus replaces the need for browsersync completely.

Would love to hear how often and prefered workflow for people that regulary use the addon.

**Comment by tyler36** [comment]
Closing.

#60 reworked the docs and includes a "Auto-start the watcher server" section. 

There seems to be little call for "auto-start" to be the default.

**Comment by rfay** [comment]
Thanks for maintaining this! There is in fact expectation of auto-start that we see doing support, but I think it's important to keep the default what you like it to be.

**Comment by tyler36** [comment]
I do hear some requests in discord and slack; hence #60 
I guess I don't hear from people who are happy with the current (non-autostart) implmentation.

This issue was open for 3months with no feedback here so the issue was closed based on that. Happy to discuss here or else where.

**Comment by rfay** [comment]
I think your approach is fine, and thanks for explaining how to do the auto-start in #60
